server:
  port: 8082
spring:
  application:
    name: usability
  datasource:
    url: jdbc:postgresql://postgres-usability:5432/usabilitydb
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka
