server:
  port: 8081
spring:
  application:
    name: participants
  datasource:
    url: jdbc:postgresql://localhost:5432/participantsdb
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
