server:
  port: 8081
spring:
  application:
    name: participants
  datasource:
    url: jdbc:postgresql://postgres-participants:5432/participantsdb
    username: postgres
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

external:
  usability:
    api:
      base-url: ${EXTERNAL_USABILITY_API_BASEURL:http://gateway:8080}
